s={10,20,30,40,50}
q={80,90,10}
s.add('abc')
print(s)
s.pop()
print(s)
s.remove(30)
print(s)
x=s-q
print(x)
y=q-s
print(y)
x=q.difference(s)
print(x)
z=q^s
print(z)
r=q.difference_update(s)
print(r)
print(q)
q.symmetric_difference_update(s)
print(s)
c={10,20,30,40}
d={60,70,80}
c.symmetric_difference_update(d)
print(c)
u=q.intersection_update(s)
print(q)
v=q.union(s)
print(v)
s.update(c)
print(s)
print(c.isdisjoint(d))
print(d.isdisjoint(q))
print(c.issubset(d))
print(c.issuperset(d))
print(c>=s)